//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRMSupportForce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailSOQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailSOQLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCRMSupportForce.DetailSOQLQueries", typeof(DetailSOQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(Id)
        ///From Contact 
        ///where causeview__Date_of_Last_Gift__c &gt;= {0:yyyy-MM-dd}  
        ///and causeview__Date_of_Last_Gift__c &lt;= {1:yyyy-MM-dd}.
        /// </summary>
        internal static string DonorCountQ {
            get {
                return ResourceManager.GetString("DonorCountQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetContactsBySolicitor {
            get {
                return ResourceManager.GetString("GetContactsBySolicitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, AccountId, causeview__Constituent_ID__c, causeview__Donor__c,  causeview__Major_Gift_Donor__c, Description, Email, FirstName, HasOptedOutOfEmail, LastName, MailingAddress, MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet, Middle_Name__c, MobilePhone, Name, Phone, Salutation,Title,Why_They_Support_OCRM__c, causeview__Anonymous__c, causeview__Deceased__c, Communication_Preference__c, IsDeleted, Telemarketing__c,causeview__Date_of_Last_Gift__c 
        ///From Contact 
        ///.
        /// </summary>
        internal static string GetDonorByID {
            get {
                return ResourceManager.GetString("GetDonorByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(causeview__payment__r.causeview__Donation__r.Id)
        ///from causeview__Gift_Detail__c
        ///where causeview__payment__r.causeview__Date__c  &gt;= {0:yyyy-MM-dd}
        ///and causeview__payment__r.causeview__Date__c &lt;={1:yyyy-MM-dd}.
        /// </summary>
        internal static string PaymentCountQ {
            get {
                return ResourceManager.GetString("PaymentCountQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, AccountId, causeview__Constituent_ID__c, causeview__Donor__c,  causeview__Major_Gift_Donor__c, Description, Email, FirstName, HasOptedOutOfEmail, LastName, MailingAddress, MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet, Middle_Name__c, MobilePhone, Name, Phone, Salutation,Title,Why_They_Support_OCRM__c, causeview__Anonymous__c, causeview__Deceased__c, Communication_Preference__c, IsDeleted, Telemarketing__c,causeview__Date_of_Last_Gift__c 
        ///From Contact 
        ///where causev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PopulateDonorTable {
            get {
                return ResourceManager.GetString("PopulateDonorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///causeview__payment__c,
        ///causeview__Payment__r.causeview__amount__c,
        ///causeview__payment__r.causeview__Date__c,
        ///causeview__Fund__c,
        ///causeview__Payment__r.causeview__Donation__r.causeview__Constituent__c,
        ///causeview__Payment__r.causeview__Donation__r.causeview__Organization__c,
        ///causeview__Campaign__r.Id,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.Internal_Solicitor__c,
        ///causeview__payment__r.causeview__Donation__r.causeview__Gift_Type__c
        ///from causeview__Gift_Detail__c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PopulatePaymentTable {
            get {
                return ResourceManager.GetString("PopulatePaymentTable", resourceCulture);
            }
        }
    }
}
