//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRMSupportForce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LclQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LclQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCRMSupportForce.LclQueries", typeof(LclQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(ID) from ocrm.donors where ocrm.donors.ID =.
        /// </summary>
        internal static string DonorExistsQ {
            get {
                return ResourceManager.GetString("DonorExistsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ocrm.campaigns values (@IDParam,@StartDateParam,@EndDateParam,@TypeParam).
        /// </summary>
        internal static string InsertCampaignRecord {
            get {
                return ResourceManager.GetString("InsertCampaignRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ocrm.donors values(@IDPARAM, @NAMEPARAM, @PHONEPARAM, @EMAILPARAM, 
        ///@ADDRPARAM, @CITYPARAM, @STATEPARAM, @ZIPPARAM, @HASDONATEDPARAM, @ISMAJORGIFTSPARAM, @DESCRIPTIONPARAM, @FIRSTNAMEPARAM, @EMAILOPTOUTPARAM, @LASTNAMEPARAM, @MIDDLENAMEPARAM, @MOBILEPHONEPARAM, @SALUTATIONPARAM, @TITLEPARAM, @WHYSUPPORTPARAM, @ANONYMOUSPARAM, @DECEASEDPARAM, @COMMPREFERENCEPARAM, @DELETEDPARAM, @TELEMARKETINGNOTESPARAM,@LASTDONATIONDATEPARAM, @CONSTITUENTIDPARAM, @ACCOUNTIDPARAM,@MATCHKEYPARAM).
        /// </summary>
        internal static string InsertDonorRecord {
            get {
                return ResourceManager.GetString("InsertDonorRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT into paymentsummary values (@MATCHKEYPARAM, @CALYEARPARAM, @TOTALDONATIONSPARAM).
        /// </summary>
        internal static string InsertMatchKeyRecord {
            get {
                return ResourceManager.GetString("InsertMatchKeyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into ocrm.Payments
        ///Values(@IDPARAM, @AMOUNTPARAM, @RECDATEPARAM,@FUNDIDPARAM,@DONORIDPARAM,@GIFTTYPEPARAM, @SOLICITORPARAM, @CAMPAIGNPARAM).
        /// </summary>
        internal static string InsertPaymentRecord {
            get {
                return ResourceManager.GetString("InsertPaymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(DISTINCT d.ID) 
        ///from ocrm.donors d
        ///where LastDonationDate &lt;= @ENDDATEPARAM and LastDonationDate &gt;= @BEGINDATEPARAM.
        /// </summary>
        internal static string LapsedDonorCountQ {
            get {
                return ResourceManager.GetString("LapsedDonorCountQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///(select max(Amount) from payments where donorId = @DONORIDPARAM) as LARGESTGIFT,
        ///(select Amount from payments where donorId = @DONORIDPARAM 
        ///order by Recieved_Date desc LIMIT 1) as LASTGIFT, 
        ///(select count(Id) from Payments where donorId = @DONORIDPARAM) as FREQUENCY,
        ///(Select sum(Amount) from payments where donorId = @DONORIDPARAM) as LIFETIMEGIVING,
        ///(Select max(Solicitor) from payments where donorId = @DONORIDPARAM) as SOLICITOR.
        /// </summary>
        internal static string LapsedGivingQ {
            get {
                return ResourceManager.GetString("LapsedGivingQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID, Internal_Solicitor__c FROM Contact
        ///where Internal_Solicitor__c = &apos;{0}&apos;.
        /// </summary>
        internal static string LoadSolicitorContactsQ {
            get {
                return ResourceManager.GetString("LoadSolicitorContactsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(matchkey) from paymentsummary where matchkey = &apos;{0}&apos; and calyear = {1}.
        /// </summary>
        internal static string MatchkeyExistsQ {
            get {
                return ResourceManager.GetString("MatchkeyExistsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(ID) from ocrm.Payments where ID =  .
        /// </summary>
        internal static string PaymentExistsQ {
            get {
                return ResourceManager.GetString("PaymentExistsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, Name, Salutation, FirstName, LastName, StreetAddress, City, State, ZipCode,
        ///Phone, LastDonationDate, Telemarketing_Notes, MobilePhone, Causeview_ID from donors
        ///where LastDonationDate &gt;= @BeginDateParam
        ///and LastDonationDate &lt;= @EndDateParam LIMIT 100000.
        /// </summary>
        internal static string SelectLapsedDonors {
            get {
                return ResourceManager.GetString("SelectLapsedDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update ocrm.campaigns
        ///set StartDate = @StartDateParam,
        ///EndDate = @EndDateParam,
        ///Type = @TypeParam
        ///where ID = @IDParam.
        /// </summary>
        internal static string UpdateCampaignRecord {
            get {
                return ResourceManager.GetString("UpdateCampaignRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update ocrm.donors
        ///set Name = @NAMEPARAM,
        ///Phone = @PHONEPARAM,
        ///Email = @EMAILPARAM,
        ///StreetAddress = @ADDRPARAM,
        ///City = @CITYPARAM,
        ///State = @STATEPARAM,
        ///ZipCode = @ZIPPARAM,
        ///IsDonor = @HASDONATEDPARAM, 
        ///MajorGifts = @ISMAJORGIFTSPARAM, 
        ///Description = @DESCRIPTIONPARAM, 
        ///FirstName = @FIRSTNAMEPARAM, 
        ///EmailOptOut = @EMAILOPTOUTPARAM, 
        ///LastName = @LASTNAMEPARAM, 
        ///MiddleName = @MIDDLENAMEPARAM, 
        ///MobilePhone = @MOBILEPHONEPARAM, 
        ///Salutation = @SALUTATIONPARAM, 
        ///Title = @TITLEPARAM, 
        ///WhySupport = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDonorRecord {
            get {
                return ResourceManager.GetString("UpdateDonorRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update paymentsummary set totaldonations = @TOTALDONATIONSPARAM where matchkey = @MATCHKEYPARAM and calyear = @CALYEARPARAM.
        /// </summary>
        internal static string UpdateMatchKeyRecord {
            get {
                return ResourceManager.GetString("UpdateMatchKeyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ocrm.Payments
        ///set Amount = @AMOUNTPARAM,
        ///Recieved_Date = @RECDATEPARAM,
        ///FundID = @FUNDIDPARAM,
        ///DonorID = @DONORIDPARAM,
        ///Gift_Type = @GIFTTYPEPARAM,
        ///Solicitor = @SOLICITORPARAM,
        ///Campaign = @CAMPAIGNPARAM
        ///Where ID = @IDPARAM.
        /// </summary>
        internal static string UpdatePaymentRecord {
            get {
                return ResourceManager.GetString("UpdatePaymentRecord", resourceCulture);
            }
        }
    }
}
