//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRMSupportForce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCRMSupportForce.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT count(Id)
        ///from Contact
        ///Where 
        ///causeview__Date_of_Last_Gift__c &gt;= {0:yyyy-MM-dd}
        ///and causeview__Date_of_Last_Gift__c &lt;= {1:yyyy-MM-dd}.
        /// </summary>
        public static string DonorCountQ {
            get {
                return ResourceManager.GetString("DonorCountQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighthouse.
        /// </summary>
        public static string ForcePassword {
            get {
                return ResourceManager.GetString("ForcePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peEuG5mCPRZeIHji8V0xCN5O.
        /// </summary>
        public static string ForceToken {
            get {
                return ResourceManager.GetString("ForceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shannon.Dias@rescuemission.org.
        /// </summary>
        public static string ForceUser {
            get {
                return ResourceManager.GetString("ForceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT causeview__Fund_Name__c FROM causeview__Fund__c.
        /// </summary>
        public static string FundSelectQ {
            get {
                return ResourceManager.GetString("FundSelectQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sum(causeview__Amount__c),
        ///max(causeview__Date__c),
        ///causeview__Donation__r.causeview__Constituent__r.Internal_Solicitor__c,  
        ///causeview__Donation__r.causeview__Constituent__r.causeview__primary_Addressee__c,
        ///causeview__Donation__r.causeview__Constituent__r.mailingStreet,
        ///causeview__Donation__r.causeview__Constituent__r.mailingCity,
        ///causeview__Donation__r.causeview__Constituent__r.mailingPostalCode,
        ///causeview__Donation__r.causeview__Constituent__r.mailingState,
        ///causeview__Donation__r.causeview [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndBasicQ {
            get {
                return ResourceManager.GetString("IndBasicQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group by 
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.Internal_Solicitor__c,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.causeview__primary_Addressee__c,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.mailingStreet,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.mailingCity,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.mailingPostalCode,
        ///causeview__payment__r.causeview__Donat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string INQGroupClause {
            get {
                return ResourceManager.GetString("INQGroupClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///sum(causeview__payment__r.causeview__Amount__c),
        ///max(causeview__payment__r.causeview__Date__c),
        ///max(causeview__payment__r.causeview__Amount__c),
        ///min(causeview__payment__r.causeview__Amount__c),
        ///count(causeview__payment__c),
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.causeview__primary_Addressee__c,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.mailingStreet,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.mailingCity [rest of string was truncated]&quot;;.
        /// </summary>
        public static string INQSelectClause {
            get {
                return ResourceManager.GetString("INQSelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group by 
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.name,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingStreet,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingCity,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingPostalCode,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingState,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrgQGroupClause {
            get {
                return ResourceManager.GetString("OrgQGroupClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///sum(causeview__payment__r.causeview__Amount__c),
        ///max(causeview__payment__r.causeview__Date__c),
        ///max(causeview__payment__r.causeview__Amount__c),
        ///min(causeview__payment__r.causeview__Amount__c),
        ///count(causeview__payment__c),
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.name,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingStreet,
        ///causeview__payment__r.causeview__Donation__r.causeview__Organization__r.BillingCity,
        ///causeview__payment__r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrgQSelectClause {
            get {
                return ResourceManager.GetString("OrgQSelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(causeview__payment__r.causeview__Donation__r.Id)
        ///from causeview__Gift_Detail__c
        ///where causeview__payment__r.causeview__Date__c  &gt;= {0:yyyy-MM-dd}
        ///and causeview__payment__r.causeview__Date__c &lt;={1:yyyy-MM-dd}
        ///and causeview__payment__r.causeview__Donation__r.causeview__Constituent__c &lt;&gt; null.
        /// </summary>
        public static string PaymentCountQ {
            get {
                return ResourceManager.GetString("PaymentCountQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///Id,causeview__primary_Addressee__c,
        ///mailingStreet,
        ///mailingCity,
        ///mailingPostalCode,
        ///mailingState,
        ///Email,
        ///Phone
        ///from Contact.
        /// </summary>
        public static string RecentDonorSelect {
            get {
                return ResourceManager.GetString("RecentDonorSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///causeview__payment__c,
        ///causeview__Payment__r.causeview__amount__c,
        ///causeview__payment__r.causeview__Date__c,
        ///causeview__Fund__c,
        ///causeview__Payment__r.causeview__Donation__r.causeview__Constituent__c,
        ///causeview__Campaign__r.Id,
        ///causeview__payment__r.causeview__Donation__r.causeview__Constituent__r.Internal_Solicitor__c,
        ///causeview__payment__r.causeview__Donation__r.causeview__Gift_Type__c
        ///from causeview__Gift_Detail__c
        ///where causeview__payment__r.causeview__Date__c &gt;= {0:yyyy-MM-dd}
        ///and ca [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RecentPaymentSelect {
            get {
                return ResourceManager.GetString("RecentPaymentSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT causeview__Amount__c, causeview__Constituent__c  
        ///FROM causeview__Payment__c
        ///where causeview__Date__c &gt; 2014-12-31
        ///LIMIT 10.
        /// </summary>
        public static string TestQ {
            get {
                return ResourceManager.GetString("TestQ", resourceCulture);
            }
        }
    }
}
